INSERT INTO Tags(id, name) VALUES (28,'swordsman');
INSERT INTO Tags(id, name) VALUES (32,'vampire');
INSERT INTO Tags(id, name) VALUES (72,'student council president');
INSERT INTO Tags(id, name) VALUES (99,'dandere');
INSERT INTO Tags(id, name) VALUES (105,'street fighter');
INSERT INTO Tags(id, name) VALUES (106,'capcom');
INSERT INTO Tags(id, name) VALUES (117,'british');
INSERT INTO Tags(id, name) VALUES (140,'cyborg');
INSERT INTO Tags(id, name) VALUES (155,'fire powers');
INSERT INTO Tags(id, name) VALUES (158,'kitsune');
INSERT INTO Tags(id, name) VALUES (162,'assassin');
INSERT INTO Tags(id, name) VALUES (167,'chinese');
INSERT INTO Tags(id, name) VALUES (168,'amazon');
INSERT INTO Tags(id, name) VALUES (180,'pigtails');
INSERT INTO Tags(id, name) VALUES (184,'singer');
INSERT INTO Tags(id, name) VALUES (186,'cop');
INSERT INTO Tags(id, name) VALUES (187,'robot');
INSERT INTO Tags(id, name) VALUES (191,'strong');
INSERT INTO Tags(id, name) VALUES (201,'nurse');
INSERT INTO Tags(id, name) VALUES (206,'purple eyes');
INSERT INTO Tags(id, name) VALUES (215,'knight');
INSERT INTO Tags(id, name) VALUES (218,'agent');
INSERT INTO Tags(id, name) VALUES (221,'umbrella');
INSERT INTO Tags(id, name) VALUES (232,'tan');
INSERT INTO Tags(id, name) VALUES (235,'tomboy');
INSERT INTO Tags(id, name) VALUES (245,'gray hair');
INSERT INTO Tags(id, name) VALUES (246,'cruiser');
INSERT INTO Tags(id, name) VALUES (248,'warship');
INSERT INTO Tags(id, name) VALUES (268,'yuri');
INSERT INTO Tags(id, name) VALUES (277,'eyebrows');
INSERT INTO Tags(id, name) VALUES (283,'housewife');
INSERT INTO Tags(id, name) VALUES (290,'psychic');
INSERT INTO Tags(id, name) VALUES (291,'brunette');
INSERT INTO Tags(id, name) VALUES (295,'gold third');
INSERT INTO Tags(id, name) VALUES (301,'keyboardist');
INSERT INTO Tags(id, name) VALUES (305,'masochist');
INSERT INTO Tags(id, name) VALUES (312,'dragon');
INSERT INTO Tags(id, name) VALUES (319,'crossdresser');
INSERT INTO Tags(id, name) VALUES (320,'guitarist');
INSERT INTO Tags(id, name) VALUES (324,'himedere');
INSERT INTO Tags(id, name) VALUES (326,'pegasus knight');
INSERT INTO Tags(id, name) VALUES (327,'prince');
INSERT INTO Tags(id, name) VALUES (331,'archer');
INSERT INTO Tags(id, name) VALUES (334,'fujoshi');
INSERT INTO Tags(id, name) VALUES (340,'samurai');
INSERT INTO Tags(id, name) VALUES (343,'boatgirl');
INSERT INTO Tags(id, name) VALUES (344,'kunoichi');
INSERT INTO Tags(id, name) VALUES (347,'dullahan');
INSERT INTO Tags(id, name) VALUES (349,'sniper');
INSERT INTO Tags(id, name) VALUES (350,'centaur');
INSERT INTO Tags(id, name) VALUES (354,'mage');
INSERT INTO Tags(id, name) VALUES (366,'french');
INSERT INTO Tags(id, name) VALUES (374,'tail');
INSERT INTO Tags(id, name) VALUES (390,'angel');
INSERT INTO Tags(id, name) VALUES (397,'stand');
INSERT INTO Tags(id, name) VALUES (402,'skeleton');
INSERT INTO Tags(id, name) VALUES (409,'crimson demon');
INSERT INTO Tags(id, name) VALUES (418,'cowboy');
INSERT INTO Tags(id, name) VALUES (420,'ghost');
INSERT INTO Tags(id, name) VALUES (442,'pianist');
INSERT INTO Tags(id, name) VALUES (444,'diver');
INSERT INTO Tags(id, name) VALUES (445,'secretary');
INSERT INTO Tags(id, name) VALUES (457,'korean');
INSERT INTO Tags(id, name) VALUES (469,'detective');
INSERT INTO Tags(id, name) VALUES (471,'hime cut');
INSERT INTO Tags(id, name) VALUES (479,'dragon ball');
INSERT INTO Tags(id, name) VALUES (484,'spy');
INSERT INTO Tags(id, name) VALUES (488,'blue');
INSERT INTO Tags(id, name) VALUES (492,'space');
INSERT INTO Tags(id, name) VALUES (494,'saiyan');
INSERT INTO Tags(id, name) VALUES (495,'evil');
INSERT INTO Tags(id, name) VALUES (498,'bikes');
INSERT INTO Tags(id, name) VALUES (499,'justice');
INSERT INTO Tags(id, name) VALUES (503,'racer');
INSERT INTO Tags(id, name) VALUES (517,'medic');
INSERT INTO Tags(id, name) VALUES (518,'hotd');
INSERT INTO Tags(id, name) VALUES (532,'monster girl');
INSERT INTO Tags(id, name) VALUES (548,'thighs');
INSERT INTO Tags(id, name) VALUES (551,'final fantasy');
INSERT INTO Tags(id, name) VALUES (568,'gintama');
INSERT INTO Tags(id, name) VALUES (569,'clone');
INSERT INTO Tags(id, name) VALUES (647,'pink eyes');
INSERT INTO Tags(id, name) VALUES (649,'quiet');
INSERT INTO Tags(id, name) VALUES (651,'bookworm');
INSERT INTO Tags(id, name) VALUES (667,'actress');
INSERT INTO Tags(id, name) VALUES (671,'undead');
INSERT INTO Tags(id, name) VALUES (679,'shonen jump');
INSERT INTO Tags(id, name) VALUES (693,'exorcist');
INSERT INTO Tags(id, name) VALUES (702,'mole');
INSERT INTO Tags(id, name) VALUES (704,'author');
INSERT INTO Tags(id, name) VALUES (712,'clumsy');
INSERT INTO Tags(id, name) VALUES (717,'class president');
INSERT INTO Tags(id, name) VALUES (718,'rabbit');
INSERT INTO Tags(id, name) VALUES (719,'stoic');
INSERT INTO Tags(id, name) VALUES (726,'sister complex');
INSERT INTO Tags(id, name) VALUES (727,'sports club manager');
INSERT INTO Tags(id, name) VALUES (739,'club president');
INSERT INTO Tags(id, name) VALUES (741,'idol fan');
INSERT INTO Tags(id, name) VALUES (762,'model');
INSERT INTO Tags(id, name) VALUES (766,'μ''s');
INSERT INTO Tags(id, name) VALUES (779,'buns');
INSERT INTO Tags(id, name) VALUES (798,'bibi');
INSERT INTO Tags(id, name) VALUES (804,'murderer');
INSERT INTO Tags(id, name) VALUES (827,'dragon ball super');
INSERT INTO Tags(id, name) VALUES (828,'eyepatch');
INSERT INTO Tags(id, name) VALUES (839,'ringlets');
INSERT INTO Tags(id, name) VALUES (850,'mirai nikki');
INSERT INTO Tags(id, name) VALUES (867,'officer');
INSERT INTO Tags(id, name) VALUES (868,'mother');
INSERT INTO Tags(id, name) VALUES (869,'blue skin');
INSERT INTO Tags(id, name) VALUES (934,'cooking');
INSERT INTO Tags(id, name) VALUES (957,'hostess');
INSERT INTO Tags(id, name) VALUES (996,'Aqours');
INSERT INTO Tags(id, name) VALUES (1002,'Musician');
INSERT INTO Tags(id, name) VALUES (1003,'Mecha Pilot');
INSERT INTO Tags(id, name) VALUES (1005,'Martial Artist');
INSERT INTO Tags(id, name) VALUES (1007,'Fairy');
INSERT INTO Tags(id, name) VALUES (1008,'Villian');
INSERT INTO Tags(id, name) VALUES (1009,'Clown');
INSERT INTO Tags(id, name) VALUES (1010,'Alien');
INSERT INTO Tags(id, name) VALUES (1012,'red hair');
INSERT INTO Tags(id, name) VALUES (1014,'blue hair');
INSERT INTO Tags(id, name) VALUES (1016,'yellow eyes');
INSERT INTO Tags(id, name) VALUES (1020,'purple hair');
INSERT INTO Tags(id, name) VALUES (1021,'pink hair');
INSERT INTO Tags(id, name) VALUES (1024,'scientist');
INSERT INTO Tags(id, name) VALUES (1025,'black eyes');
INSERT INTO Tags(id, name) VALUES (1026,'blackhair');
INSERT INTO Tags(id, name) VALUES (1027,'white hair');
INSERT INTO Tags(id, name) VALUES (1028,'heterochromia');
INSERT INTO Tags(id, name) VALUES (1029,'large breasts');
INSERT INTO Tags(id, name) VALUES (1031,'twintails');
INSERT INTO Tags(id, name) VALUES (1033,'flat chest');
INSERT INTO Tags(id, name) VALUES (1034,'lazy');
INSERT INTO Tags(id, name) VALUES (1035,'ahoge');
INSERT INTO Tags(id, name) VALUES (1036,'airhead');
INSERT INTO Tags(id, name) VALUES (1037,'ponytail');
INSERT INTO Tags(id, name) VALUES (1038,'kimono');
INSERT INTO Tags(id, name) VALUES (1039,'demon');
INSERT INTO Tags(id, name) VALUES (1040,'chuunibyou');
INSERT INTO Tags(id, name) VALUES (1041,'orange hair');
INSERT INTO Tags(id, name) VALUES (1042,'teacher');
INSERT INTO Tags(id, name) VALUES (1043,'succubus');
INSERT INTO Tags(id, name) VALUES (1044,'magical girl');
INSERT INTO Tags(id, name) VALUES (1045,'idol');
INSERT INTO Tags(id, name) VALUES (1046,'side ponytail');
INSERT INTO Tags(id, name) VALUES (1047,'little sister');
INSERT INTO Tags(id, name) VALUES (1048,'orange eyes');
INSERT INTO Tags(id, name) VALUES (1049,'grey hair');
INSERT INTO Tags(id, name) VALUES (1050,'hairband');
INSERT INTO Tags(id, name) VALUES (1052,'childhood friend');
INSERT INTO Tags(id, name) VALUES (1053,'half elf');
INSERT INTO Tags(id, name) VALUES (1054,'scarf');
INSERT INTO Tags(id, name) VALUES (1055,'twin tails');
INSERT INTO Tags(id, name) VALUES (1056,'grey eyes');
INSERT INTO Tags(id, name) VALUES (1057,'yandere');
INSERT INTO Tags(id, name) VALUES (1058,'goddess');
INSERT INTO Tags(id, name) VALUES (1059,'futanari');
INSERT INTO Tags(id, name) VALUES (1060,'flat');
INSERT INTO Tags(id, name) VALUES (1061,'yellow hair');
INSERT INTO Tags(id, name) VALUES (1062,'sister');
INSERT INTO Tags(id, name) VALUES (1063,'lolita fashion');
INSERT INTO Tags(id, name) VALUES (1064,'athlete');
INSERT INTO Tags(id, name) VALUES (1065,'split personality');
INSERT INTO Tags(id, name) VALUES (1067,'time traveller');
INSERT INTO Tags(id, name) VALUES (1068,'esper');
INSERT INTO Tags(id, name) VALUES (1069,'cyan hair');
INSERT INTO Tags(id, name) VALUES (1070,'otaku');
INSERT INTO Tags(id, name) VALUES (1071,'mangaka');
INSERT INTO Tags(id, name) VALUES (1072,'blind');
INSERT INTO Tags(id, name) VALUES (1073,'scars');
INSERT INTO Tags(id, name) VALUES (1074,'artist');
INSERT INTO Tags(id, name) VALUES (1075,'deaf');
INSERT INTO Tags(id, name) VALUES (1076,'sarcastic');
INSERT INTO Tags(id, name) VALUES (1077,'hikikomori');
INSERT INTO Tags(id, name) VALUES (1078,'dark skin');
INSERT INTO Tags(id, name) VALUES (1079,'houseki no kuni');
INSERT INTO Tags(id, name) VALUES (1094,'blonde hairs');
INSERT INTO Tags(id, name) VALUES (1095,'megane');
INSERT INTO Tags(id, name) VALUES (1097,'asocial');
INSERT INTO Tags(id, name) VALUES (1098,'gray eyes');
INSERT INTO Tags(id, name) VALUES (1099,'imouto');
INSERT INTO Tags(id, name) VALUES (1100,'moe fang');
INSERT INTO Tags(id, name) VALUES (1101,'sportist');
INSERT INTO Tags(id, name) VALUES (1102,'rapunzel hair');
INSERT INTO Tags(id, name) VALUES (1103,'gar');
INSERT INTO Tags(id, name) VALUES (1104,'zettai ryouiki');
INSERT INTO Tags(id, name) VALUES (1105,'braid');
INSERT INTO Tags(id, name) VALUES (1106,'onee-san');
INSERT INTO Tags(id, name) VALUES (1107,'gender bender');
INSERT INTO Tags(id, name) VALUES (1108,'non human');
INSERT INTO Tags(id, name) VALUES (1109,'tattoo');
INSERT INTO Tags(id, name) VALUES (1110,'based on a real person');
INSERT INTO Tags(id, name) VALUES (1111,'dad');
INSERT INTO Tags(id, name) VALUES (1112,'mad scientist');
INSERT INTO Tags(id, name) VALUES (1113,'mask');
INSERT INTO Tags(id, name) VALUES (1114,'swag');
INSERT INTO Tags(id, name) VALUES (1115,'lamia');
INSERT INTO Tags(id, name) VALUES (1116,'cyclops');
INSERT INTO Tags(id, name) VALUES (1117,'mermaid');
INSERT INTO Tags(id, name) VALUES (1118,'headband');
INSERT INTO Tags(id, name) VALUES (1119,'oni');
INSERT INTO Tags(id, name) VALUES (1120,'dryad');
INSERT INTO Tags(id, name) VALUES (1121,'horns');
INSERT INTO Tags(id, name) VALUES (1122,'unicorn');
INSERT INTO Tags(id, name) VALUES (1123,'lolita');
INSERT INTO Tags(id, name) VALUES (1124,'sadist');
INSERT INTO Tags(id, name) VALUES (1126,'pale skin');
INSERT INTO Tags(id, name) VALUES (1127,'sex hair');
INSERT INTO Tags(id, name) VALUES (1128,'witch');
INSERT INTO Tags(id, name) VALUES (1129,'odango');
INSERT INTO Tags(id, name) VALUES (1130,'kind');
INSERT INTO Tags(id, name) VALUES (1131,'android');
INSERT INTO Tags(id, name) VALUES (1132,'derivative');
INSERT INTO Tags(id, name) VALUES (1133,'spanish');
INSERT INTO Tags(id, name) VALUES (1134,'cat');
INSERT INTO Tags(id, name) VALUES (1135,'black fur');
INSERT INTO Tags(id, name) VALUES (1136,'queen');
INSERT INTO Tags(id, name) VALUES (1137,'red eye');
INSERT INTO Tags(id, name) VALUES (1138,'green eye');
INSERT INTO Tags(id, name) VALUES (1139,'desu');
INSERT INTO Tags(id, name) VALUES (1140,'invisible');
INSERT INTO Tags(id, name) VALUES (1141,'saint');
INSERT INTO Tags(id, name) VALUES (1142,'hat');
INSERT INTO Tags(id, name) VALUES (1143,'magenta hair');
INSERT INTO Tags(id, name) VALUES (1145,'hair ornament');
INSERT INTO Tags(id, name) VALUES (1146,'kuudere');
INSERT INTO Tags(id, name) VALUES (1147,'scar');
INSERT INTO Tags(id, name) VALUES (1148,'animal');
INSERT INTO Tags(id, name) VALUES (1149,'dog');
INSERT INTO Tags(id, name) VALUES (1150,'penguin');
INSERT INTO Tags(id, name) VALUES (1152,'bassist');
INSERT INTO Tags(id, name) VALUES (1153,'drummer');
INSERT INTO Tags(id, name) VALUES (1154,'gyaru');
INSERT INTO Tags(id, name) VALUES (1155,'big sister');
INSERT INTO Tags(id, name) VALUES (1156,'male');
INSERT INTO Tags(id, name) VALUES (1157,'yangire');
INSERT INTO Tags(id, name) VALUES (1158,'god');
INSERT INTO Tags(id, name) VALUES (1159,'virtual avatar');
INSERT INTO Tags(id, name) VALUES (1161,'maid outfit');
INSERT INTO Tags(id, name) VALUES (1162,'glutton');
INSERT INTO Tags(id, name) VALUES (1163,'beautiful hair');
INSERT INTO Tags(id, name) VALUES (1164,'adult');
INSERT INTO Tags(id, name) VALUES (1166,'big breasts');
INSERT INTO Tags(id, name) VALUES (1167,'teen');
INSERT INTO Tags(id, name) VALUES (1169,'swiss');
INSERT INTO Tags(id, name) VALUES (1170,'long hair');
INSERT INTO Tags(id, name) VALUES (1171,'egyptian');
INSERT INTO Tags(id, name) VALUES (1172,'mexican');
INSERT INTO Tags(id, name) VALUES (1173,'half-japanese');
INSERT INTO Tags(id, name) VALUES (1175,'school swimming club member');
INSERT INTO Tags(id, name) VALUES (1177,'eye patch');
INSERT INTO Tags(id, name) VALUES (1178,'cosplayer');
INSERT INTO Tags(id, name) VALUES (1180,'drama club member');
INSERT INTO Tags(id, name) VALUES (1181,'youkai');
INSERT INTO Tags(id, name) VALUES (1182,'american');
INSERT INTO Tags(id, name) VALUES (1183,'deity');
INSERT INTO Tags(id, name) VALUES (1184,'flirt');
INSERT INTO Tags(id, name) VALUES (1185,'gothic lolita');
INSERT INTO Tags(id, name) VALUES (1186,'magic user');
INSERT INTO Tags(id, name) VALUES (1187,'australian');
INSERT INTO Tags(id, name) VALUES (1188,'maid');
INSERT INTO Tags(id, name) VALUES (1189,'hair drills');
INSERT INTO Tags(id, name) VALUES (1190,'perverted');
INSERT INTO Tags(id, name) VALUES (1191,'oneesan');
INSERT INTO Tags(id, name) VALUES (1192,'magician');
INSERT INTO Tags(id, name) VALUES (1193,'ribbon');
INSERT INTO Tags(id, name) VALUES (1194,'tennis player');
INSERT INTO Tags(id, name) VALUES (1197,'gorilla');
INSERT INTO Tags(id, name) VALUES (1198,'russian');
INSERT INTO Tags(id, name) VALUES (1199,'braids');
INSERT INTO Tags(id, name) VALUES (1200,'swedish');
INSERT INTO Tags(id, name) VALUES (1201,'honest');
INSERT INTO Tags(id, name) VALUES (1202,'straight-forward');
INSERT INTO Tags(id, name) VALUES (1203,'confident');
INSERT INTO Tags(id, name) VALUES (1204,'student council');
INSERT INTO Tags(id, name) VALUES (1205,'science club member');
INSERT INTO Tags(id, name) VALUES (1206,'short-tempered');
INSERT INTO Tags(id, name) VALUES (1207,'turquoise hair');
INSERT INTO Tags(id, name) VALUES (1208,'selfish');
INSERT INTO Tags(id, name) VALUES (1209,'irish');
INSERT INTO Tags(id, name) VALUES (1210,'brazilian');
INSERT INTO Tags(id, name) VALUES (1211,'bald');
INSERT INTO Tags(id, name) VALUES (1212,'a special boy');
INSERT INTO Tags(id, name) VALUES (1213,'swordswoman');
INSERT INTO Tags(id, name) VALUES (1214,'busty blonde');
INSERT INTO Tags(id, name) VALUES (1216,'dark elf');
INSERT INTO Tags(id, name) VALUES (1217,'pointy ears');
INSERT INTO Tags(id, name) VALUES (1218,'hair antenna');
INSERT INTO Tags(id, name) VALUES (1220,'psychopath');
INSERT INTO Tags(id, name) VALUES (1221,'adventurer');
INSERT INTO Tags(id, name) VALUES (1222,'noble');
INSERT INTO Tags(id, name) VALUES (1223,'hair ribbons');
INSERT INTO Tags(id, name) VALUES (1224,'wealthy');
INSERT INTO Tags(id, name) VALUES (1225,'head bands');
INSERT INTO Tags(id, name) VALUES (1226,'mischievous');
INSERT INTO Tags(id, name) VALUES (1227,'cook');
INSERT INTO Tags(id, name) VALUES (1228,'hot-headed');
INSERT INTO Tags(id, name) VALUES (1229,'inventor');
INSERT INTO Tags(id, name) VALUES (1230,'brocon');
INSERT INTO Tags(id, name) VALUES (1231,'brother complex');
INSERT INTO Tags(id, name) VALUES (1232,'big eater');
INSERT INTO Tags(id, name) VALUES (1233,'gardener');
INSERT INTO Tags(id, name) VALUES (1234,'silver hair');
INSERT INTO Tags(id, name) VALUES (1235,'headmaster');
INSERT INTO Tags(id, name) VALUES (1236,'school principal');
INSERT INTO Tags(id, name) VALUES (1237,'spear');
INSERT INTO Tags(id, name) VALUES (1238,'midriff');
INSERT INTO Tags(id, name) VALUES (1239,'jungle');
INSERT INTO Tags(id, name) VALUES (1240,'loincloth');
INSERT INTO Tags(id, name) VALUES (1241,'knife');
INSERT INTO Tags(id, name) VALUES (1242,'snake');
INSERT INTO Tags(id, name) VALUES (1243,'priestess');
INSERT INTO Tags(id, name) VALUES (1244,'dancer');
INSERT INTO Tags(id, name) VALUES (1245,'pirate');
INSERT INTO Tags(id, name) VALUES (1246,'mischievious');
INSERT INTO Tags(id, name) VALUES (1247,'patient');
INSERT INTO Tags(id, name) VALUES (1248,'smart');
INSERT INTO Tags(id, name) VALUES (1249,'dog owner');
INSERT INTO Tags(id, name) VALUES (1250,'bounty hunter');
INSERT INTO Tags(id, name) VALUES (1251,'smoker');
INSERT INTO Tags(id, name) VALUES (1252,'deceased');
INSERT INTO Tags(id, name) VALUES (1253,'overweight');
INSERT INTO Tags(id, name) VALUES (1255,'colored lock of hair');
INSERT INTO Tags(id, name) VALUES (1256,'dark-skinned');
INSERT INTO Tags(id, name) VALUES (1257,'earrings');
INSERT INTO Tags(id, name) VALUES (1258,'shapeshifter');
INSERT INTO Tags(id, name) VALUES (1259,'tsundere');
INSERT INTO Tags(id, name) VALUES (1260,'light brown hair');
INSERT INTO Tags(id, name) VALUES (1261,'black hair');
INSERT INTO Tags(id, name) VALUES (1262,'red eyes');
INSERT INTO Tags(id, name) VALUES (1263,'yugioh');
INSERT INTO Tags(id, name) VALUES (1264,'blue-eyes white dragon');
INSERT INTO Tags(id, name) VALUES (1265,'kisara');
INSERT INTO Tags(id, name) VALUES (1266,'lightsworn');
INSERT INTO Tags(id, name) VALUES (1267,'ls');
INSERT INTO Tags(id, name) VALUES (1268,'jugdment');
INSERT INTO Tags(id, name) VALUES (1269,'tipita');
INSERT INTO Tags(id, name) VALUES (1270,'beard');
INSERT INTO Tags(id, name) VALUES (1271,'villain');
INSERT INTO Tags(id, name) VALUES (1272,'cat ears');
INSERT INTO Tags(id, name) VALUES (1273,'communist');
INSERT INTO Tags(id, name) VALUES (1274,'communism');
INSERT INTO Tags(id, name) VALUES (1276,'elder');
INSERT INTO Tags(id, name) VALUES (1277,'old');
INSERT INTO Tags(id, name) VALUES (1278,'blonde');
INSERT INTO Tags(id, name) VALUES (1279,'teenager');
INSERT INTO Tags(id, name) VALUES (1280,'ribbons');
INSERT INTO Tags(id, name) VALUES (1281,'shameless');
INSERT INTO Tags(id, name) VALUES (1282,'high school student');
INSERT INTO Tags(id, name) VALUES (1283,'child');
INSERT INTO Tags(id, name) VALUES (1284,'half wolf');
INSERT INTO Tags(id, name) VALUES (1285,'small stature');
INSERT INTO Tags(id, name) VALUES (1287,'beige hair');
INSERT INTO Tags(id, name) VALUES (1288,'fallen angel');
INSERT INTO Tags(id, name) VALUES (1289,'soldier');
INSERT INTO Tags(id, name) VALUES (1290,'twin');
INSERT INTO Tags(id, name) VALUES (1291,'genius');
INSERT INTO Tags(id, name) VALUES (1292,'racist');
INSERT INTO Tags(id, name) VALUES (1293,'gladiator');
INSERT INTO Tags(id, name) VALUES (1294,'student council member');
INSERT INTO Tags(id, name) VALUES (1295,'kendō club member');
INSERT INTO Tags(id, name) VALUES (1296,'heiress');
INSERT INTO Tags(id, name) VALUES (1297,'wife');
INSERT INTO Tags(id, name) VALUES (1298,'cell');
INSERT INTO Tags(id, name) VALUES (1299,'390');
INSERT INTO Tags(id, name) VALUES (1300,'code: 390');
INSERT INTO Tags(id, name) VALUES (1301,'argentea');
INSERT INTO Tags(id, name) VALUES (1302,'pistil');
INSERT INTO Tags(id, name) VALUES (1303,'hacker');
INSERT INTO Tags(id, name) VALUES (1304,'multicolored hair');
INSERT INTO Tags(id, name) VALUES (1305,'neko');
INSERT INTO Tags(id, name) VALUES (1306,'student');
INSERT INTO Tags(id, name) VALUES (1307,'medusa');
INSERT INTO Tags(id, name) VALUES (1308,'sphinx');
INSERT INTO Tags(id, name) VALUES (1309,'superhero');
INSERT INTO Tags(id, name) VALUES (1310,'abs');
INSERT INTO Tags(id, name) VALUES (1311,'artifical intelligence');
INSERT INTO Tags(id, name) VALUES (1312,'government agent');
INSERT INTO Tags(id, name) VALUES (1313,'live action');
INSERT INTO Tags(id, name) VALUES (1314,'comic book');
INSERT INTO Tags(id, name) VALUES (1316,'wizard');
INSERT INTO Tags(id, name) VALUES (1317,'literature');
INSERT INTO Tags(id, name) VALUES (1318,'sorcerer');
INSERT INTO Tags(id, name) VALUES (1319,'tattoos');
INSERT INTO Tags(id, name) VALUES (1320,'tabletop rpg');
INSERT INTO Tags(id, name) VALUES (1321,'non-human');
INSERT INTO Tags(id, name) VALUES (1323,'jedi');
INSERT INTO Tags(id, name) VALUES (1324,'delinquent');
INSERT INTO Tags(id, name) VALUES (1325,'yankee');
INSERT INTO Tags(id, name) VALUES (1326,'attorney');
INSERT INTO Tags(id, name) VALUES (1327,'prosecutor');
INSERT INTO Tags(id, name) VALUES (1328,'eldritch horror');
INSERT INTO Tags(id, name) VALUES (1329,'tentacle hair');
INSERT INTO Tags(id, name) VALUES (1330,'fortune teller');
INSERT INTO Tags(id, name) VALUES (1331,'artificial intelligence');
INSERT INTO Tags(id, name) VALUES (1332,'kendo practitioner');
INSERT INTO Tags(id, name) VALUES (1333,'bad cook');
INSERT INTO Tags(id, name) VALUES (1334,'barkeep');
INSERT INTO Tags(id, name) VALUES (1335,'freedom fighter');
INSERT INTO Tags(id, name) VALUES (1336,'terrorist');
INSERT INTO Tags(id, name) VALUES (1337,'acrobat');
INSERT INTO Tags(id, name) VALUES (1338,'circus performer');
INSERT INTO Tags(id, name) VALUES (1339,'mutant');
INSERT INTO Tags(id, name) VALUES (1340,'inhuman');
INSERT INTO Tags(id, name) VALUES (1341,'quirk');
INSERT INTO Tags(id, name) VALUES (1342,'pervert');
INSERT INTO Tags(id, name) VALUES (1343,'kryptonian');
INSERT INTO Tags(id, name) VALUES (1344,'metahuman');
INSERT INTO Tags(id, name) VALUES (1345,'new god');
INSERT INTO Tags(id, name) VALUES (1346,'elf');
INSERT INTO Tags(id, name) VALUES (1347,'blond hair');
INSERT INTO Tags(id, name) VALUES (1348,'chainsaw');
INSERT INTO Tags(id, name) VALUES (1349,'pro wrestler');
INSERT INTO Tags(id, name) VALUES (1350,'kage');
INSERT INTO Tags(id, name) VALUES (1351,'healer');
INSERT INTO Tags(id, name) VALUES (1352,'barbarian');
INSERT INTO Tags(id, name) VALUES (1353,'pathfinder');
INSERT INTO Tags(id, name) VALUES (1354,'16-year-old');
INSERT INTO Tags(id, name) VALUES (1356,'gold eyes');
INSERT INTO Tags(id, name) VALUES (1357,'artificial lifeform');
INSERT INTO Tags(id, name) VALUES (1358,'bandages');
INSERT INTO Tags(id, name) VALUES (1360,'short');
INSERT INTO Tags(id, name) VALUES (1361,'lavender hair');
INSERT INTO Tags(id, name) VALUES (1362,'writer');
INSERT INTO Tags(id, name) VALUES (1363,'cetra');
INSERT INTO Tags(id, name) VALUES (1364,'editor');
INSERT INTO Tags(id, name) VALUES (1365,'blue eye');
INSERT INTO Tags(id, name) VALUES (1366,'boxer');
INSERT INTO Tags(id, name) VALUES (1368,'alchemist');
INSERT INTO Tags(id, name) VALUES (1369,'military');
INSERT INTO Tags(id, name) VALUES (1370,'mustache');
INSERT INTO Tags(id, name) VALUES (1371,'muscles');
INSERT INTO Tags(id, name) VALUES (1372,'sparkles');
INSERT INTO Tags(id, name) VALUES (1373,'catgirl');
INSERT INTO Tags(id, name) VALUES (1374,'married');
INSERT INTO Tags(id, name) VALUES (1375,'shopkeeper');
INSERT INTO Tags(id, name) VALUES (1378,'onmipotent');
INSERT INTO Tags(id, name) VALUES (1379,'cloudcuckoolander');
INSERT INTO Tags(id, name) VALUES (1380,'anthropomorphic cat');
INSERT INTO Tags(id, name) VALUES (1381,'blood type b');
INSERT INTO Tags(id, name) VALUES (1382,'bear');
INSERT INTO Tags(id, name) VALUES (1383,'bandage');
INSERT INTO Tags(id, name) VALUES (1384,'bikini');
INSERT INTO Tags(id, name) VALUES (1385,'maid uniform');
INSERT INTO Tags(id, name) VALUES (1386,'scythe');
INSERT INTO Tags(id, name) VALUES (1387,'stockings');
INSERT INTO Tags(id, name) VALUES (1388,'intelligent');
INSERT INTO Tags(id, name) VALUES (1389,'pokemon trainer');
INSERT INTO Tags(id, name) VALUES (1390,'principal');
INSERT INTO Tags(id, name) VALUES (1391,'anthropomorphic ship');
INSERT INTO Tags(id, name) VALUES (1392,'narcissist');
INSERT INTO Tags(id, name) VALUES (1393,'spirit');
INSERT INTO Tags(id, name) VALUES (1394,'bakeneko');
INSERT INTO Tags(id, name) VALUES (1395,'touhou');
INSERT INTO Tags(id, name) VALUES (1396,'wings');
INSERT INTO Tags(id, name) VALUES (1397,'valkyrie');
INSERT INTO Tags(id, name) VALUES (1398,'anthropomorphic fox');
INSERT INTO Tags(id, name) VALUES (1399,'arbiter');
INSERT INTO Tags(id, name) VALUES (1400,'middle eastern');
INSERT INTO Tags(id, name) VALUES (1401,'disney');
INSERT INTO Tags(id, name) VALUES (1402,'blood type ab');
INSERT INTO Tags(id, name) VALUES (1403,'blood type o');
INSERT INTO Tags(id, name) VALUES (1404,'bread');
INSERT INTO Tags(id, name) VALUES (1405,'german');
INSERT INTO Tags(id, name) VALUES (1406,'third eye');
INSERT INTO Tags(id, name) VALUES (1407,'chef');
INSERT INTO Tags(id, name) VALUES (1408,'baker');
INSERT INTO Tags(id, name) VALUES (1409,'asari');
INSERT INTO Tags(id, name) VALUES (1410,'criminal');
INSERT INTO Tags(id, name) VALUES (1411,'shrine maiden');
INSERT INTO Tags(id, name) VALUES (1412,'wolf');
INSERT INTO Tags(id, name) VALUES (1413,'bird');
INSERT INTO Tags(id, name) VALUES (1414,'mech suit');
INSERT INTO Tags(id, name) VALUES (1415,'freckles');
INSERT INTO Tags(id, name) VALUES (1416,'dealer');
INSERT INTO Tags(id, name) VALUES (1417,'gambler');
INSERT INTO Tags(id, name) VALUES (1418,'choker');
INSERT INTO Tags(id, name) VALUES (1419,'heavy drinker');
INSERT INTO Tags(id, name) VALUES (1420,'doctor');
INSERT INTO Tags(id, name) VALUES (1421,'astronaut');
INSERT INTO Tags(id, name) VALUES (1422,'supervillain');
INSERT INTO Tags(id, name) VALUES (1423,'lingerie');
INSERT INTO Tags(id, name) VALUES (1424,'cat eyes');
INSERT INTO Tags(id, name) VALUES (1425,'anthropomorphic gun');
INSERT INTO Tags(id, name) VALUES (1426,'waitress');
INSERT INTO Tags(id, name) VALUES (1427,'16 year old');
INSERT INTO Tags(id, name) VALUES (1428,'water magic');
INSERT INTO Tags(id, name) VALUES (1429,'game designer');
INSERT INTO Tags(id, name) VALUES (1430,'university student');
INSERT INTO Tags(id, name) VALUES (1431,'class representative');
INSERT INTO Tags(id, name) VALUES (1432,'nobility');
INSERT INTO Tags(id, name) VALUES (1433,'staff');
INSERT INTO Tags(id, name) VALUES (1434,'caveman');
INSERT INTO Tags(id, name) VALUES (1435,'business owner');
INSERT INTO Tags(id, name) VALUES (1436,'draph');
INSERT INTO Tags(id, name) VALUES (1437,'shinai');
INSERT INTO Tags(id, name) VALUES (1438,'mechanic');
INSERT INTO Tags(id, name) VALUES (1439,'driver');
INSERT INTO Tags(id, name) VALUES (1440,'student council vice-president');
INSERT INTO Tags(id, name) VALUES (1441,'christian');
INSERT INTO Tags(id, name) VALUES (1442,'17 year old');
INSERT INTO Tags(id, name) VALUES (1443,'beauty mark');
INSERT INTO Tags(id, name) VALUES (1444,'librarian');
INSERT INTO Tags(id, name) VALUES (1445,'servant');
INSERT INTO Tags(id, name) VALUES (1446,'32 year old');
INSERT INTO Tags(id, name) VALUES (1447,'ai');
INSERT INTO Tags(id, name) VALUES (1448,'pink-hair');
INSERT INTO Tags(id, name) VALUES (1449,'father');
INSERT INTO Tags(id, name) VALUES (1450,'green skin');
INSERT INTO Tags(id, name) VALUES (1451,'buck teeth');
INSERT INTO Tags(id, name) VALUES (1452,'goth');
INSERT INTO Tags(id, name) VALUES (1453,'coach');
INSERT INTO Tags(id, name) VALUES (1454,'mountain climber');
INSERT INTO Tags(id, name) VALUES (1455,'elemental');
INSERT INTO Tags(id, name) VALUES (1456,'fire elemental');
INSERT INTO Tags(id, name) VALUES (1457,'homunculus');
INSERT INTO Tags(id, name) VALUES (1458,'mute');
INSERT INTO Tags(id, name) VALUES (1459,'whip');
INSERT INTO Tags(id, name) VALUES (1460,'planeswalker');
INSERT INTO Tags(id, name) VALUES (1461,'pyromancer');
INSERT INTO Tags(id, name) VALUES (1462,'suit');
INSERT INTO Tags(id, name) VALUES (1463,'chubby');
INSERT INTO Tags(id, name) VALUES (1465,'heroes');
INSERT INTO Tags(id, name) VALUES (1466,'hero');
INSERT INTO Tags(id, name) VALUES (1467,'blong hair');
INSERT INTO Tags(id, name) VALUES (1468,'blong hair');
INSERT INTO Tags(id, name) VALUES (1469,'furry');
INSERT INTO Tags(id, name) VALUES (1470,'pokemon');
INSERT INTO Tags(id, name) VALUES (1471,'advertising mascot');
INSERT INTO Tags(id, name) VALUES (1472,'transformation');
INSERT INTO Tags(id, name) VALUES (1473,'mahjong player');
INSERT INTO Tags(id, name) VALUES (1474,'half-elf');
INSERT INTO Tags(id, name) VALUES (1475,'monster hunter');
INSERT INTO Tags(id, name) VALUES (1476,'demon slayer');
INSERT INTO Tags(id, name) VALUES (1477,'tengu');
INSERT INTO Tags(id, name) VALUES (1478,'reporter');
INSERT INTO Tags(id, name) VALUES (1479,'journalist');
INSERT INTO Tags(id, name) VALUES (1480,'25 year old');
INSERT INTO Tags(id, name) VALUES (1481,'wind instruments club member');
INSERT INTO Tags(id, name) VALUES (1482,'lesbian');
INSERT INTO Tags(id, name) VALUES (1483,'siscon');
INSERT INTO Tags(id, name) VALUES (1484,'sensha-do team member');
INSERT INTO Tags(id, name) VALUES (1485,'bicycle club member');
INSERT INTO Tags(id, name) VALUES (1486,'devil');
INSERT INTO Tags(id, name) VALUES (1487,'club owner');
INSERT INTO Tags(id, name) VALUES (1488,'tea club member');
INSERT INTO Tags(id, name) VALUES (1489,'tea club president');
INSERT INTO Tags(id, name) VALUES (1490,'ojou');
INSERT INTO Tags(id, name) VALUES (1491,'sees member');
INSERT INTO Tags(id, name) VALUES (1492,'animal ears');
INSERT INTO Tags(id, name) VALUES (1493,'ghoul');
INSERT INTO Tags(id, name) VALUES (1494,'avatar');
INSERT INTO Tags(id, name) VALUES (1495,'bender');
INSERT INTO Tags(id, name) VALUES (1496,'horn');
INSERT INTO Tags(id, name) VALUES (1497,'martian');
INSERT INTO Tags(id, name) VALUES (1498,'hypertopian');
INSERT INTO Tags(id, name) VALUES (1500,'kawaii');
INSERT INTO Tags(id, name) VALUES (1501,'manager');
INSERT INTO Tags(id, name) VALUES (1502,'sidekick');
INSERT INTO Tags(id, name) VALUES (1503,'nun');
INSERT INTO Tags(id, name) VALUES (1504,'11 year old');
INSERT INTO Tags(id, name) VALUES (1505,'6th grade');
INSERT INTO Tags(id, name) VALUES (1506,'eiken club member');
INSERT INTO Tags(id, name) VALUES (1507,'tanar''ri');
INSERT INTO Tags(id, name) VALUES (1508,'23 year old');
INSERT INTO Tags(id, name) VALUES (1509,'fox');
INSERT INTO Tags(id, name) VALUES (1510,'fennec fox');
INSERT INTO Tags(id, name) VALUES (1511,'red panda');
INSERT INTO Tags(id, name) VALUES (1512,'hyena');
INSERT INTO Tags(id, name) VALUES (1513,'secretary bird');
INSERT INTO Tags(id, name) VALUES (1514,'norn');
INSERT INTO Tags(id, name) VALUES (1515,'jurian');
INSERT INTO Tags(id, name) VALUES (1516,'drow');
INSERT INTO Tags(id, name) VALUES (1517,'dhampir');
INSERT INTO Tags(id, name) VALUES (1518,'intra-terrestrial');
INSERT INTO Tags(id, name) VALUES (1519,'cakey');
INSERT INTO Tags(id, name) VALUES (1520,'best girl');
INSERT INTO Tags(id, name) VALUES (1521,'marvel');
INSERT INTO Tags(id, name) VALUES (1522,'domino');
INSERT INTO Tags(id, name) VALUES (1523,'minotaur');
INSERT INTO Tags(id, name) VALUES (1524,'burmecian');
INSERT INTO Tags(id, name) VALUES (1525,'viera');
INSERT INTO Tags(id, name) VALUES (1526,'kemonomimi');
INSERT INTO Tags(id, name) VALUES (1527,'fishman');
INSERT INTO Tags(id, name) VALUES (1528,'reindeer');
INSERT INTO Tags(id, name) VALUES (1529,'devil fruit user');
INSERT INTO Tags(id, name) VALUES (1530,'goblin');
INSERT INTO Tags(id, name) VALUES (1531,'warrior');
INSERT INTO Tags(id, name) VALUES (1532,'bikini armor');
INSERT INTO Tags(id, name) VALUES (1533,'cross dresser');
INSERT INTO Tags(id, name) VALUES (1534,'engineer');
INSERT INTO Tags(id, name) VALUES (1535,'dominatrix');
INSERT INTO Tags(id, name) VALUES (1536,'femdom');
INSERT INTO Tags(id, name) VALUES (1537,'shojo');
INSERT INTO Tags(id, name) VALUES (1539,'arachne');
INSERT INTO Tags(id, name) VALUES (1540,'slime');
INSERT INTO Tags(id, name) VALUES (1541,'harpy');
INSERT INTO Tags(id, name) VALUES (1542,'stitches');
INSERT INTO Tags(id, name) VALUES (1543,'ogre');
INSERT INTO Tags(id, name) VALUES (1544,'monoeye');
INSERT INTO Tags(id, name) VALUES (1545,'kobold');
INSERT INTO Tags(id, name) VALUES (1546,'dragonewt');
INSERT INTO Tags(id, name) VALUES (1547,'pan');
INSERT INTO Tags(id, name) VALUES (1548,'twi''lek');
INSERT INTO Tags(id, name) VALUES (1549,'sith');
INSERT INTO Tags(id, name) VALUES (1550,'dathomirian');
INSERT INTO Tags(id, name) VALUES (1551,'clockwork');
INSERT INTO Tags(id, name) VALUES (1552,'yordle');
INSERT INTO Tags(id, name) VALUES (1553,'vastayan');
INSERT INTO Tags(id, name) VALUES (1554,'half-dragon');
INSERT INTO Tags(id, name) VALUES (1555,'plant');
INSERT INTO Tags(id, name) VALUES (1556,'tree');
INSERT INTO Tags(id, name) VALUES (1557,'togruta');
INSERT INTO Tags(id, name) VALUES (1558,'jerk');
INSERT INTO Tags(id, name) VALUES (1559,'asshole');
INSERT INTO Tags(id, name) VALUES (1560,'creep');
INSERT INTO Tags(id, name) VALUES (1561,'mentor');
INSERT INTO Tags(id, name) VALUES (1562,'yakuza');
INSERT INTO Tags(id, name) VALUES (1563,'programmer');
INSERT INTO Tags(id, name) VALUES (1564,'lucky');
INSERT INTO Tags(id, name) VALUES (1565,'unlucky');
INSERT INTO Tags(id, name) VALUES (1566,'animal breeder');
INSERT INTO Tags(id, name) VALUES (1567,'animal companion');
INSERT INTO Tags(id, name) VALUES (1568,'arrogant');
INSERT INTO Tags(id, name) VALUES (1569,'heir');
INSERT INTO Tags(id, name) VALUES (1570,'coward');
INSERT INTO Tags(id, name) VALUES (1571,'yuki-onna');
INSERT INTO Tags(id, name) VALUES (1572,'yokai');
INSERT INTO Tags(id, name) VALUES (1573,'newspaper club member');
INSERT INTO Tags(id, name) VALUES (1574,'oral fixation');
INSERT INTO Tags(id, name) VALUES (1575,'doppelganger');
INSERT INTO Tags(id, name) VALUES (1576,'pleiades member');
INSERT INTO Tags(id, name) VALUES (1577,'lizardfolk');
INSERT INTO Tags(id, name) VALUES (1578,'automaton');
INSERT INTO Tags(id, name) VALUES (1579,'battle maid');
INSERT INTO Tags(id, name) VALUES (1580,'arachnid');
INSERT INTO Tags(id, name) VALUES (1581,'werewolf');
INSERT INTO Tags(id, name) VALUES (1582,'lycanthrope');
INSERT INTO Tags(id, name) VALUES (1583,'scorpion demon');
INSERT INTO Tags(id, name) VALUES (1584,'dumb');
INSERT INTO Tags(id, name) VALUES (1585,'fusion');
INSERT INTO Tags(id, name) VALUES (1586,'tiefling');
INSERT INTO Tags(id, name) VALUES (1587,'survey corps');
INSERT INTO Tags(id, name) VALUES (1588,'titan shifter');
INSERT INTO Tags(id, name) VALUES (1589,'information broker');
INSERT INTO Tags(id, name) VALUES (1590,'pony');
INSERT INTO Tags(id, name) VALUES (1591,'alicorn');
INSERT INTO Tags(id, name) VALUES (1592,'pegasus');
INSERT INTO Tags(id, name) VALUES (1593,'earth pony');
INSERT INTO Tags(id, name) VALUES (1594,'hyperactive');
INSERT INTO Tags(id, name) VALUES (1595,'athletic');
INSERT INTO Tags(id, name) VALUES (1597,'seamstress');
INSERT INTO Tags(id, name) VALUES (1598,'farmer');
INSERT INTO Tags(id, name) VALUES (1600,'laconic');
INSERT INTO Tags(id, name) VALUES (1601,'shy');
INSERT INTO Tags(id, name) VALUES (1602,'toon');
INSERT INTO Tags(id, name) VALUES (1603,'ragdoll');
INSERT INTO Tags(id, name) VALUES (1604,'construct');
INSERT INTO Tags(id, name) VALUES (1605,'toy');
INSERT INTO Tags(id, name) VALUES (1606,'doll');
INSERT INTO Tags(id, name) VALUES (1607,'soul reaper');
INSERT INTO Tags(id, name) VALUES (1608,'shinigami');
INSERT INTO Tags(id, name) VALUES (1609,'arrancar');
INSERT INTO Tags(id, name) VALUES (1610,'espada');
INSERT INTO Tags(id, name) VALUES (1611,'underboobs');
INSERT INTO Tags(id, name) VALUES (1612,'mod-soul');
INSERT INTO Tags(id, name) VALUES (1613,'zanpakuto');
INSERT INTO Tags(id, name) VALUES (1614,'bount');
INSERT INTO Tags(id, name) VALUES (1615,'saber');
INSERT INTO Tags(id, name) VALUES (1616,'rider');
INSERT INTO Tags(id, name) VALUES (1617,'alter');
INSERT INTO Tags(id, name) VALUES (1618,'caster');
INSERT INTO Tags(id, name) VALUES (1619,'lancer');
INSERT INTO Tags(id, name) VALUES (1620,'polar bear dog');
INSERT INTO Tags(id, name) VALUES (1621,'hanyo');
INSERT INTO Tags(id, name) VALUES (1622,'cabbit');
INSERT INTO Tags(id, name) VALUES (1623,'spaceship');
INSERT INTO Tags(id, name) VALUES (1624,'artifical humanoid');
INSERT INTO Tags(id, name) VALUES (1625,'realian');
INSERT INTO Tags(id, name) VALUES (1627,'small');
INSERT INTO Tags(id, name) VALUES (1628,'deredere');
INSERT INTO Tags(id, name) VALUES (1629,'rich');
INSERT INTO Tags(id, name) VALUES (1630,'si');
INSERT INTO Tags(id, name) VALUES (1631,'pompadour');
INSERT INTO Tags(id, name) VALUES (1633,'blacksmith');
INSERT INTO Tags(id, name) VALUES (1634,'bandit');
INSERT INTO Tags(id, name) VALUES (1635,'bunny ears');
INSERT INTO Tags(id, name) VALUES (1636,'mercenary');
INSERT INTO Tags(id, name) VALUES (1637,'slave');
INSERT INTO Tags(id, name) VALUES (1638,'great dane');
INSERT INTO Tags(id, name) VALUES (1639,'pixie');
INSERT INTO Tags(id, name) VALUES (1640,'persona');
INSERT INTO Tags(id, name) VALUES (1641,'fate');
INSERT INTO Tags(id, name) VALUES (1642,'greek');
INSERT INTO Tags(id, name) VALUES (1643,'reptile');
INSERT INTO Tags(id, name) VALUES (1644,'koopa');
INSERT INTO Tags(id, name) VALUES (1645,'tiger');
INSERT INTO Tags(id, name) VALUES (1646,'anthropomorphic tiger');
INSERT INTO Tags(id, name) VALUES (1647,'mascot');
INSERT INTO Tags(id, name) VALUES (1648,'king');
INSERT INTO Tags(id, name) VALUES (1649,'hamster');
INSERT INTO Tags(id, name) VALUES (1650,'cyberdoll');
INSERT INTO Tags(id, name) VALUES (1651,'middle school student');
INSERT INTO Tags(id, name) VALUES (1652,'bro-con');
INSERT INTO Tags(id, name) VALUES (1653,'office lady');
INSERT INTO Tags(id, name) VALUES (1654,'digital devil saga');
INSERT INTO Tags(id, name) VALUES (1655,'megami tensei');
INSERT INTO Tags(id, name) VALUES (1656,'megaten');
INSERT INTO Tags(id, name) VALUES (1657,'hook');
INSERT INTO Tags(id, name) VALUES (1658,'mummy');
INSERT INTO Tags(id, name) VALUES (1659,'dinogirl');
INSERT INTO Tags(id, name) VALUES (1660,'dinosaur girl');
INSERT INTO Tags(id, name) VALUES (1661,'orphan');
INSERT INTO Tags(id, name) VALUES (1662,'softball club member');
INSERT INTO Tags(id, name) VALUES (1663,'amber eyes');
INSERT INTO Tags(id, name) VALUES (1664,'anbu');
INSERT INTO Tags(id, name) VALUES (1665,'anthropomorphic squid');
INSERT INTO Tags(id, name) VALUES (1666,'26 year old');
INSERT INTO Tags(id, name) VALUES (1667,'ojou laugh');
INSERT INTO Tags(id, name) VALUES (1668,'elite four');
INSERT INTO Tags(id, name) VALUES (1669,'dwarf');
INSERT INTO Tags(id, name) VALUES (1670,'announcer');
INSERT INTO Tags(id, name) VALUES (1671,'bibliophile');
INSERT INTO Tags(id, name) VALUES (1672,'paper master');
INSERT INTO Tags(id, name) VALUES (1673,'secret agent');
INSERT INTO Tags(id, name) VALUES (1675,'italian');
INSERT INTO Tags(id, name) VALUES (1676,'convict');
INSERT INTO Tags(id, name) VALUES (1677,'class 2-c');
INSERT INTO Tags(id, name) VALUES (1678,'hentai');
INSERT INTO Tags(id, name) VALUES (1681,'zora');
INSERT INTO Tags(id, name) VALUES (1682,'fish person');
INSERT INTO Tags(id, name) VALUES (1683,'class 1-d');
INSERT INTO Tags(id, name) VALUES (1684,'anthropomorphic rabbit');
INSERT INTO Tags(id, name) VALUES (1685,'extradimensional');
INSERT INTO Tags(id, name) VALUES (1686,'japanese');
INSERT INTO Tags(id, name) VALUES (1687,'tank');
INSERT INTO Tags(id, name) VALUES (1688,'class 1-b');
INSERT INTO Tags(id, name) VALUES (1689,'silver eyes');
INSERT INTO Tags(id, name) VALUES (1691,'29 year old');
INSERT INTO Tags(id, name) VALUES (1692,'swim team member');
INSERT INTO Tags(id, name) VALUES (1693,'tennis club member');
INSERT INTO Tags(id, name) VALUES (1694,'skateboarder');
INSERT INTO Tags(id, name) VALUES (1696,'bisexual');
INSERT INTO Tags(id, name) VALUES (1697,'library club member');
INSERT INTO Tags(id, name) VALUES (1698,'calligraphy club member');
INSERT INTO Tags(id, name) VALUES (1699,'voice actress');
INSERT INTO Tags(id, name) VALUES (1700,'class 3-3');
INSERT INTO Tags(id, name) VALUES (1701,'junior high school student');
INSERT INTO Tags(id, name) VALUES (1702,'wrestler');
INSERT INTO Tags(id, name) VALUES (1703,'kami');
INSERT INTO Tags(id, name) VALUES (1704,'porn star');
INSERT INTO Tags(id, name) VALUES (1705,'eccentric');
INSERT INTO Tags(id, name) VALUES (1706,'neet');
INSERT INTO Tags(id, name) VALUES (1707,'amputee');
INSERT INTO Tags(id, name) VALUES (1708,'skater');
INSERT INTO Tags(id, name) VALUES (1709,'korean american');
INSERT INTO Tags(id, name) VALUES (1710,'fisherman');
INSERT INTO Tags(id, name) VALUES (1712,'boston terrier');
INSERT INTO Tags(id, name) VALUES (1713,'reploid');
INSERT INTO Tags(id, name) VALUES (1714,'serious');
INSERT INTO Tags(id, name) VALUES (1715,'cyan eyes');
INSERT INTO Tags(id, name) VALUES (1716,'antlers');
INSERT INTO Tags(id, name) VALUES (1717,'internet celebrity');
INSERT INTO Tags(id, name) VALUES (1718,'digimon');
INSERT INTO Tags(id, name) VALUES (1719,'armor');
INSERT INTO Tags(id, name) VALUES (1720,'motorcyclist');
INSERT INTO Tags(id, name) VALUES (1721,'courier');
INSERT INTO Tags(id, name) VALUES (1722,'student council vice president');
INSERT INTO Tags(id, name) VALUES (1723,'space ship');
INSERT INTO Tags(id, name) VALUES (1724,'hologram');
INSERT INTO Tags(id, name) VALUES (1725,'indian-american');
INSERT INTO Tags(id, name) VALUES (1726,'philanthropist');
INSERT INTO Tags(id, name) VALUES (1727,'socialite');
INSERT INTO Tags(id, name) VALUES (1728,'geokinetic');
INSERT INTO Tags(id, name) VALUES (1729,'sorceress');
INSERT INTO Tags(id, name) VALUES (1730,'14 year old');
INSERT INTO Tags(id, name) VALUES (1731,'borg');
INSERT INTO Tags(id, name) VALUES (1732,'varisian');
INSERT INTO Tags(id, name) VALUES (1733,'x-men member');
INSERT INTO Tags(id, name) VALUES (1734,'avengers member');
INSERT INTO Tags(id, name) VALUES (1735,'hispanic');
INSERT INTO Tags(id, name) VALUES (1736,'oppai loli');
INSERT INTO Tags(id, name) VALUES (1737,'shopkeep');
INSERT INTO Tags(id, name) VALUES (1738,'star of destiny');
INSERT INTO Tags(id, name) VALUES (1739,'crane');
INSERT INTO Tags(id, name) VALUES (1740,'magic club member');
INSERT INTO Tags(id, name) VALUES (1741,'magic club president');
INSERT INTO Tags(id, name) VALUES (1742,'wight');
INSERT INTO Tags(id, name) VALUES (1743,'class 2-7');
INSERT INTO Tags(id, name) VALUES (1744,'office worker');
INSERT INTO Tags(id, name) VALUES (1745,'haniwa research club member');
INSERT INTO Tags(id, name) VALUES (1746,'alcoholic');
INSERT INTO Tags(id, name) VALUES (1747,'monocle');
INSERT INTO Tags(id, name) VALUES (1748,'faerie');
INSERT INTO Tags(id, name) VALUES (1749,'kylbringa');
INSERT INTO Tags(id, name) VALUES (1750,'fishnet stockings');
INSERT INTO Tags(id, name) VALUES (1751,'cheshire cat');
INSERT INTO Tags(id, name) VALUES (1752,'class 2-1');
INSERT INTO Tags(id, name) VALUES (1753,'oz');
INSERT INTO Tags(id, name) VALUES (1754,'security service');
INSERT INTO Tags(id, name) VALUES (1755,'pointed teeth');
INSERT INTO Tags(id, name) VALUES (1756,'nekomata');
INSERT INTO Tags(id, name) VALUES (1757,'twili');
INSERT INTO Tags(id, name) VALUES (1758,'anthropomorphic  gem');
INSERT INTO Tags(id, name) VALUES (1769,'flügel');
INSERT INTO Tags(id, name) VALUES (1770,'shogi player');
INSERT INTO Tags(id, name) VALUES (1771,'prostitute');
INSERT INTO Tags(id, name) VALUES (1772,'female');
INSERT INTO Tags(id, name) VALUES (1773,'police officer');
INSERT INTO Tags(id, name) VALUES (1774,'vocaloid');
INSERT INTO Tags(id, name) VALUES (1775,'#saintonii-san');
INSERT INTO Tags(id, name) VALUES (1776,'#saintyoungmen');
INSERT INTO Tags(id, name) VALUES (1777,'#saint☆young men');
INSERT INTO Tags(id, name) VALUES (1778,'saintyoungmen');
INSERT INTO Tags(id, name) VALUES (1779,'cape');
INSERT INTO Tags(id, name) VALUES (1780,'human');
INSERT INTO Tags(id, name) VALUES (1781,'class 1-8');
INSERT INTO Tags(id, name) VALUES (1782,'sumire♡16-sai!!');
INSERT INTO Tags(id, name) VALUES (1783,'tokyo 7th sisters');
INSERT INTO Tags(id, name) VALUES (1784,'brown hair');
INSERT INTO Tags(id, name) VALUES (1785,'ecstas online');
INSERT INTO Tags(id, name) VALUES (1786,'12 year old');
INSERT INTO Tags(id, name) VALUES (1787,'lunarian');
INSERT INTO Tags(id, name) VALUES (1788,'planetes');
INSERT INTO Tags(id, name) VALUES (1789,'volleyball team manager');
INSERT INTO Tags(id, name) VALUES (1790,'haikyuu!!');
INSERT INTO Tags(id, name) VALUES (1791,'fanfic character');
INSERT INTO Tags(id, name) VALUES (1792,'self insert');
INSERT INTO Tags(id, name) VALUES (1793,'blonde hair');
INSERT INTO Tags(id, name) VALUES (1794,'blue eyes');
INSERT INTO Tags(id, name) VALUES (1795,'squid girl');
INSERT INTO Tags(id, name) VALUES (1796,'anthropomorphic submarine');
INSERT INTO Tags(id, name) VALUES (1797,'azur lane');
INSERT INTO Tags(id, name) VALUES (1798,'moon angel troupe member');
INSERT INTO Tags(id, name) VALUES (1799,'22 year old');
INSERT INTO Tags(id, name) VALUES (1800,'galaxy angel');
INSERT INTO Tags(id, name) VALUES (1801,'honey eyes');
INSERT INTO Tags(id, name) VALUES (1802,'big bust');
INSERT INTO Tags(id, name) VALUES (1803,'big chest');
INSERT INTO Tags(id, name) VALUES (1804,'blue hairs');
INSERT INTO Tags(id, name) VALUES (1805,'medium hairs');
INSERT INTO Tags(id, name) VALUES (1806,'magus');
INSERT INTO Tags(id, name) VALUES (1807,'bue eyes');
INSERT INTO Tags(id, name) VALUES (1808,'code geass');
INSERT INTO Tags(id, name) VALUES (1809,'trap');
INSERT INTO Tags(id, name) VALUES (1810,'i can (ai☆kyan joukan)');
INSERT INTO Tags(id, name) VALUES (1811,'green eyes');
INSERT INTO Tags(id, name) VALUES (1812,'if her flag breaks (kanojo ga flag wo oraretara)');
INSERT INTO Tags(id, name) VALUES (1813,'ninja');
INSERT INTO Tags(id, name) VALUES (1814,'iga clan member');
INSERT INTO Tags(id, name) VALUES (1815,'basilisk');
INSERT INTO Tags(id, name) VALUES (1816,'a sky full of stars');
INSERT INTO Tags(id, name) VALUES (1817,'tower of god');
INSERT INTO Tags(id, name) VALUES (1818,'15 year old');
INSERT INTO Tags(id, name) VALUES (1819,'the idolm@ster cinderella girls');
INSERT INTO Tags(id, name) VALUES (1820,'idolmaster series');
INSERT INTO Tags(id, name) VALUES (1821,'red earth');
INSERT INTO Tags(id, name) VALUES (1822,'love me, seriously!!');
INSERT INTO Tags(id, name) VALUES (1823,'brown eyes');
INSERT INTO Tags(id, name) VALUES (1824,'fire emblem');
INSERT INTO Tags(id, name) VALUES (1825,'medaka box');
INSERT INTO Tags(id, name) VALUES (1826,'vanadis');
INSERT INTO Tags(id, name) VALUES (1827,'lord marksman and vanadis (madan no ou to vanadis)');
INSERT INTO Tags(id, name) VALUES (1828,'green hair');
INSERT INTO Tags(id, name) VALUES (1829,'my hero academia');
INSERT INTO Tags(id, name) VALUES (1830,'nanbaka (nanbaka - the numbers)');
INSERT INTO Tags(id, name) VALUES (1831,'monster');
INSERT INTO Tags(id, name) VALUES (1832,'one punch man');
INSERT INTO Tags(id, name) VALUES (1833,'dark sclera');
INSERT INTO Tags(id, name) VALUES (1834,'monster musume: everyday life with monster girls');
INSERT INTO Tags(id, name) VALUES (1835,'ryuu no haisha');
INSERT INTO Tags(id, name) VALUES (1836,'dentist');
INSERT INTO Tags(id, name) VALUES (1837,'animal crossing');
INSERT INTO Tags(id, name) VALUES (1838,'sword shaman');
INSERT INTO Tags(id, name) VALUES (1839,'lion-king member');
INSERT INTO Tags(id, name) VALUES (1840,'aria the scarlet ammo (hidan no aria)');
INSERT INTO Tags(id, name) VALUES (1841,'rwby');
INSERT INTO Tags(id, name) VALUES (1842,'metal slug');
INSERT INTO Tags(id, name) VALUES (1843,'girls'' frontline');
INSERT INTO Tags(id, name) VALUES (1844,'blood type a');
INSERT INTO Tags(id, name) VALUES (1845,'oracle');
INSERT INTO Tags(id, name) VALUES (1846,'dark souls');
INSERT INTO Tags(id, name) VALUES (1847,'edel raid');
INSERT INTO Tags(id, name) VALUES (1848,'living weapon');
INSERT INTO Tags(id, name) VALUES (1849,'series elemental gelade (erementaru jereido)');
INSERT INTO Tags(id, name) VALUES (1850,'school rumble');
INSERT INTO Tags(id, name) VALUES (1851,'dragon quest xi');
INSERT INTO Tags(id, name) VALUES (1852,'dragon quest series');
INSERT INTO Tags(id, name) VALUES (1853,'seirei no moribito');
INSERT INTO Tags(id, name) VALUES (1854,'ensemble stars!');
INSERT INTO Tags(id, name) VALUES (1855,'glasses');
INSERT INTO Tags(id, name) VALUES (1856,'tsukiuta. the animation');
INSERT INTO Tags(id, name) VALUES (1857,'kancolle: kantai collection');
INSERT INTO Tags(id, name) VALUES (1858,'black mage');
INSERT INTO Tags(id, name) VALUES (1859,'school nurse');
INSERT INTO Tags(id, name) VALUES (1860,'13 year old');
INSERT INTO Tags(id, name) VALUES (1861,'ballerina');
INSERT INTO Tags(id, name) VALUES (1862,'princess');
INSERT INTO Tags(id, name) VALUES (1863,'pilot');
INSERT INTO Tags(id, name) VALUES (1864,'calm');
INSERT INTO Tags(id, name) VALUES (1865,'high elf');
INSERT INTO Tags(id, name) VALUES (1866,'deppresive');
INSERT INTO Tags(id, name) VALUES (1868,'nazi');
INSERT INTO Tags(id, name) VALUES (1869,'worst anime');
INSERT INTO Tags(id, name) VALUES (1870,'trash');
INSERT INTO Tags(id, name) VALUES (1871,'artificial');
INSERT INTO Tags(id, name) VALUES (1872,'hello police');
INSERT INTO Tags(id, name) VALUES (1873,'husbandu');
INSERT INTO Tags(id, name) VALUES (1874,'handsome');
INSERT INTO Tags(id, name) VALUES (1875,'cutie pie');
INSERT INTO Tags(id, name) VALUES (1876,'police');
INSERT INTO Tags(id, name) VALUES (1877,'volleyball team member');
INSERT INTO Tags(id, name) VALUES (1878,'tekken');
INSERT INTO Tags(id, name) VALUES (1879,'durarara!!/drrr!!');
INSERT INTO Tags(id, name) VALUES (1880,'bartender');
INSERT INTO Tags(id, name) VALUES (1881,'bleach');
INSERT INTO Tags(id, name) VALUES (1882,'scooby-doo');
INSERT INTO Tags(id, name) VALUES (1883,'bae');
INSERT INTO Tags(id, name) VALUES (1884,'sword fighter');
INSERT INTO Tags(id, name) VALUES (1885,'firearms specialist');
INSERT INTO Tags(id, name) VALUES (1886,'sharpshooter');
INSERT INTO Tags(id, name) VALUES (1887,'cute');
INSERT INTO Tags(id, name) VALUES (1888,'eirika');
INSERT INTO Tags(id, name) VALUES (1889,'fe8');
INSERT INTO Tags(id, name) VALUES (1890,'princess zelda');
INSERT INTO Tags(id, name) VALUES (1891,'my life');
INSERT INTO Tags(id, name) VALUES (1892,'adorable');
INSERT INTO Tags(id, name) VALUES (1893,'squishy cheeks');
INSERT INTO Tags(id, name) VALUES (1894,'cool');
INSERT INTO Tags(id, name) VALUES (1895,'ash blonde hair');
INSERT INTO Tags(id, name) VALUES (1896,'magic knight');
INSERT INTO Tags(id, name) VALUES (1897,'protagonist');
INSERT INTO Tags(id, name) VALUES (1898,'violet eyes');
INSERT INTO Tags(id, name) VALUES (1899,'miko dress');
INSERT INTO Tags(id, name) VALUES (1900,'light blue eyes');
INSERT INTO Tags(id, name) VALUES (1901,'giant');
INSERT INTO Tags(id, name) VALUES (1902,'fanservice character');
INSERT INTO Tags(id, name) VALUES (1903,'huge breasts');
INSERT INTO Tags(id, name) VALUES (1904,'beartastic');
INSERT INTO Tags(id, name) VALUES (1905,'light orange hair');
INSERT INTO Tags(id, name) VALUES (1906,'mom');
INSERT INTO Tags(id, name) VALUES (1907,'lips');
INSERT INTO Tags(id, name) VALUES (1908,'fawn hair');
INSERT INTO Tags(id, name) VALUES (1909,'dark brown eyes');
INSERT INTO Tags(id, name) VALUES (1910,'black bodysuit');
INSERT INTO Tags(id, name) VALUES (1911,'cool guy');
INSERT INTO Tags(id, name) VALUES (1912,'faceless');
INSERT INTO Tags(id, name) VALUES (1913,'blond');
INSERT INTO Tags(id, name) VALUES (1914,'short hair');
INSERT INTO Tags(id, name) VALUES (1915,'bear with me');
INSERT INTO Tags(id, name) VALUES (1916,'comedian');
INSERT INTO Tags(id, name) VALUES (1917,'beautiful eyes');
INSERT INTO Tags(id, name) VALUES (1918,'impostor');
INSERT INTO Tags(id, name) VALUES (1919,'assistant');
INSERT INTO Tags(id, name) VALUES (1920,'assistant');
INSERT INTO Tags(id, name) VALUES (1921,'zombie');
INSERT INTO Tags(id, name) VALUES (1922,'future gadget lab member');
INSERT INTO Tags(id, name) VALUES (1923,'poodle');
INSERT INTO Tags(id, name) VALUES (1924,'tall');
INSERT INTO Tags(id, name) VALUES (1925,'one piece');
INSERT INTO Tags(id, name) VALUES (1926,'friendly');
INSERT INTO Tags(id, name) VALUES (1927,'idiot');
INSERT INTO Tags(id, name) VALUES (1928,'deserves to die');
INSERT INTO Tags(id, name) VALUES (1929,'too boring and too many people like him...please kill him of. ty x');
INSERT INTO Tags(id, name) VALUES (1930,'miko');
INSERT INTO Tags(id, name) VALUES (1931,'okami');
INSERT INTO Tags(id, name) VALUES (1932,'zashiki-warashi');
INSERT INTO Tags(id, name) VALUES (1933,'oppai');
INSERT INTO Tags(id, name) VALUES (1934,'gamer');
INSERT INTO Tags(id, name) VALUES (1935,'fox girl');
INSERT INTO Tags(id, name) VALUES (1936,'re: zero');
INSERT INTO Tags(id, name) VALUES (1937,'ram');
INSERT INTO Tags(id, name) VALUES (1938,'ramu');
INSERT INTO Tags(id, name) VALUES (1939,'refined');
INSERT INTO Tags(id, name) VALUES (1940,'kitsunemimi');
INSERT INTO Tags(id, name) VALUES (1941,'pure');
INSERT INTO Tags(id, name) VALUES (1942,'moe');
INSERT INTO Tags(id, name) VALUES (1943,'loli');
INSERT INTO Tags(id, name) VALUES (1944,'insane');
INSERT INTO Tags(id, name) VALUES (1945,'curly hair');
INSERT INTO Tags(id, name) VALUES (1947,'smug');
INSERT INTO Tags(id, name) VALUES (1948,'jk');
INSERT INTO Tags(id, name) VALUES (1949,'onee-chan');
INSERT INTO Tags(id, name) VALUES (1950,'fire power');
INSERT INTO Tags(id, name) VALUES (1951,'reverse trap');
INSERT INTO Tags(id, name) VALUES (1952,'pp');
INSERT INTO Tags(id, name) VALUES (1953,'necromancer');
INSERT INTO Tags(id, name) VALUES (1954,'white eyes');
INSERT INTO Tags(id, name) VALUES (1955,'side tail');
INSERT INTO Tags(id, name) VALUES (1956,'cyber');
INSERT INTO Tags(id, name) VALUES (1957,'mismatched eyes');
INSERT INTO Tags(id, name) VALUES (1958,'soulless');
INSERT INTO Tags(id, name) VALUES (1959,'silent');
INSERT INTO Tags(id, name) VALUES (1960,'friend');
INSERT INTO Tags(id, name) VALUES (1961,'skylander');
INSERT INTO Tags(id, name) VALUES (1962,'ice elemental');
INSERT INTO Tags(id, name) VALUES (1963,'water elemental');
INSERT INTO Tags(id, name) VALUES (1964,'lego');
INSERT INTO Tags(id, name) VALUES (1965,'lord');
INSERT INTO Tags(id, name) VALUES (1966,'master builder');
INSERT INTO Tags(id, name) VALUES (1967,'bomberman');
INSERT INTO Tags(id, name) VALUES (1968,'bunny');
INSERT INTO Tags(id, name) VALUES (1969,'non-binary');
INSERT INTO Tags(id, name) VALUES (1970,'moth');
INSERT INTO Tags(id, name) VALUES (1971,'what the fuck');
INSERT INTO Tags(id, name) VALUES (1972,'moustache');
INSERT INTO Tags(id, name) VALUES (1973,'literally fucking hitler');
INSERT INTO Tags(id, name) VALUES (1974,'why is this even on here');
INSERT INTO Tags(id, name) VALUES (1975,'genderless');
INSERT INTO Tags(id, name) VALUES (1976,'absolute fuckin pancake consuming machine');
INSERT INTO Tags(id, name) VALUES (1977,'shipgirl');
INSERT INTO Tags(id, name) VALUES (1978,'schoolgirl');
INSERT INTO Tags(id, name) VALUES (1979,'thigh highs');
INSERT INTO Tags(id, name) VALUES (1980,'neko tail');
INSERT INTO Tags(id, name) VALUES (1981,'cat tail');
INSERT INTO Tags(id, name) VALUES (1982,'baka');
INSERT INTO Tags(id, name) VALUES (1983,'bunny girl');
INSERT INTO Tags(id, name) VALUES (1984,'orange eye');
INSERT INTO Tags(id, name) VALUES (1985,'raifu');
INSERT INTO Tags(id, name) VALUES (1986,'eye scar');
INSERT INTO Tags(id, name) VALUES (1987,'polynesian mythology');
INSERT INTO Tags(id, name) VALUES (1988,'cinnamon roll');
INSERT INTO Tags(id, name) VALUES (1989,'psychotic');
INSERT INTO Tags(id, name) VALUES (1990,'hot');
INSERT INTO Tags(id, name) VALUES (1991,'babe');
INSERT INTO Tags(id, name) VALUES (1992,'ligma');
INSERT INTO Tags(id, name) VALUES (1993,'best');
INSERT INTO Tags(id, name) VALUES (1994,'waifu');
INSERT INTO Tags(id, name) VALUES (1995,'take this off');
INSERT INTO Tags(id, name) VALUES (1996,'trash waifu');
INSERT INTO Tags(id, name) VALUES (1997,'bad');
INSERT INTO Tags(id, name) VALUES (1998,'bad waifu');
INSERT INTO Tags(id, name) VALUES (1999,'e');
INSERT INTO Tags(id, name) VALUES (2000,'edge');
INSERT INTO Tags(id, name) VALUES (2001,'edgy');
INSERT INTO Tags(id, name) VALUES (2002,'retard');
INSERT INTO Tags(id, name) VALUES (2003,'indecisive');
INSERT INTO Tags(id, name) VALUES (2004,'gay');
INSERT INTO Tags(id, name) VALUES (2005,'non-hetero');
INSERT INTO Tags(id, name) VALUES (2006,'likes guys');
INSERT INTO Tags(id, name) VALUES (2007,'abnormal');
INSERT INTO Tags(id, name) VALUES (2008,'hikaru usada');
INSERT INTO Tags(id, name) VALUES (2009,'usada hikaru');
INSERT INTO Tags(id, name) VALUES (2010,'usagi');
INSERT INTO Tags(id, name) VALUES (2011,'rabbit costume');
INSERT INTO Tags(id, name) VALUES (2012,'nero');
INSERT INTO Tags(id, name) VALUES (2013,'mordred');
INSERT INTO Tags(id, name) VALUES (2014,'telepathic');
INSERT INTO Tags(id, name) VALUES (2015,'genderbent');
INSERT INTO Tags(id, name) VALUES (2016,'rich boi');
INSERT INTO Tags(id, name) VALUES (2017,'beauty');
INSERT INTO Tags(id, name) VALUES (2018,'fighter');
INSERT INTO Tags(id, name) VALUES (2019,'hunter');
INSERT INTO Tags(id, name) VALUES (2020,'traitor');
INSERT INTO Tags(id, name) VALUES (2021,'elegant');
INSERT INTO Tags(id, name) VALUES (2022,'dumpster');
INSERT INTO Tags(id, name) VALUES (2023,'how do i remove trash characters like this one?');
INSERT INTO Tags(id, name) VALUES (2024,'demon''s souls');
INSERT INTO Tags(id, name) VALUES (2025,'souls');
INSERT INTO Tags(id, name) VALUES (2026,'maiden');
INSERT INTO Tags(id, name) VALUES (2027,'black');
INSERT INTO Tags(id, name) VALUES (2028,'pretty gay tbh');
INSERT INTO Tags(id, name) VALUES (2029,'f');
INSERT INTO Tags(id, name) VALUES (2030,'fang');
INSERT INTO Tags(id, name) VALUES (2031,'idk fucking jesus?');
INSERT INTO Tags(id, name) VALUES (2032,'my waifu only , everyone just sucks');
INSERT INTO Tags(id, name) VALUES (2033,'thanks for listening');
INSERT INTO Tags(id, name) VALUES (2034,'meme');
INSERT INTO Tags(id, name) VALUES (2035,'troll');
INSERT INTO Tags(id, name) VALUES (2036,'homestuck');
INSERT INTO Tags(id, name) VALUES (2037,'why is this on here? i''m confused, thanks.whoever put this up , please respond in the next tag , thanks!');
INSERT INTO Tags(id, name) VALUES (2038,'transgender');
INSERT INTO Tags(id, name) VALUES (2039,'not that bad of a character');
INSERT INTO Tags(id, name) VALUES (2040,'youtuber');
INSERT INTO Tags(id, name) VALUES (2041,'anime');
INSERT INTO Tags(id, name) VALUES (2042,'random');
INSERT INTO Tags(id, name) VALUES (2043,'immortal');
INSERT INTO Tags(id, name) VALUES (2044,'ultimate waifu');
INSERT INTO Tags(id, name) VALUES (2045,'puppy');
INSERT INTO Tags(id, name) VALUES (2046,'thicc thighs');
INSERT INTO Tags(id, name) VALUES (2047,'bow');
INSERT INTO Tags(id, name) VALUES (2048,'energetic');
INSERT INTO Tags(id, name) VALUES (2049,'royalty');
INSERT INTO Tags(id, name) VALUES (2050,'ruler');
INSERT INTO Tags(id, name) VALUES (2051,'this is a waifu list not husbando list');
INSERT INTO Tags(id, name) VALUES (2052,'steven universe');
INSERT INTO Tags(id, name) VALUES (2053,'family guy');
INSERT INTO Tags(id, name) VALUES (2054,'peter griffin');
INSERT INTO Tags(id, name) VALUES (2055,'top tier');
INSERT INTO Tags(id, name) VALUES (2056,'hentaiislife');
INSERT INTO Tags(id, name) VALUES (2057,'worst girl');
